apiVersion: org.jboss.windup/v1
kind: Windup
metadata:
  name: example-windup
spec:
  resources:
    storage:
      console: 10Gi
      database: 10Gi
    cpu:
      console:
        request: 2
        limit: 4
      executor: 
        request: 1
        limit: 2
    memory:
      console:
        request: 2Gi
        limit: 4Gi
      executor: 
        request: 1Gi
        limit: 2Gi
  database:
    name: rhamt
    jndi: java:jboss/datasources/WindupServicesDS
  sso:
    publicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAhlI4WQ3tbIFE71M0HAO3TfvJFxH0P16wdOSzc/Fr9l8/tOn8cN5sgkGpnyEWcawgv2z4nouUkpV92/vo9fadKr3KVUMVaE3EaR3BmsC0Ct6TY7mYD+sz/yGoSWqwmGYocEJRIXAuMCX3jCu6CKMSV+1qjpcyYqzRaVWTB/EV76Sx+CSh9rEMLl8mE6owxNWQck03KgvWCA70l/LAu1M1bWy1aozoUKiTryX0nTxbHbj4qg3vvHC6igYndJ4zLr30QlCVn1iQ1jXC1MQUJ+Mwc8yZlkhaoAfDS1iM9I8NUcpcQAIn2baD8/aBrS1F9woYYRvo0vFH5N0+Rw4xjgSDlQIDAQAB
  images:
    externalNamespace: windup3
    tag: 4.3.1.Final