apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: windups.org.jboss.windup
spec:
  group: org.jboss.windup
  names:
    kind: Windup
    listKind: WindupList
    plural: windups
    singular: windup
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      x-kubernetes-preserve-unknown-fields: true
  versions:
  - name: v1
    served: true
    storage: true
