apiVersion: org.jboss.windup/v1
kind: Windup
metadata:
  name: example-windup
spec:
  resources:
    storage:
      console: 5Gi
      database: 5Gi
    cpu:
      console:
        request: 500m
        limit: 1
      executor: 
        request: 500m
        limit: 1
    memory:
      console:
        request: 1Gi
        limit: 2Gi
      executor: 
        request: 1Gi
        limit: 2Gi
  database:
    name: rhamt
  images:
    externalNamespace: windup3
    tag: 4.3.1.Final